baseURL: "https://joedaws.github.io"
languageCode: "en-us"
title: "Joseph Daws Jr. - Software Engineer"
theme: hugo-profile

publishDir: docs

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  # TODO FILL IN WITH BLOG LATER
  #main:
  #  - identifier: blog
  #    name: Blog
  #    title: Blog posts
  #    url: https://dev.to/
  #    weight: 1
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Joe Daws"
  description: A profile landing page for Joe Daws Jr.
  # staticPath: ""  # The path to serve the static files from
  favicon: "/crow.svg"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
     disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  color:
    textColor: \#333
    secondaryTextColor: \#306230 # used for section titles
    backgroundColor: \#d9bda5
    secondaryBackgroundColor:
    primaryColor: \#cc7722 # used for large name and some outlines
    secondaryColor: \#f6eee3

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    # brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Joe."
    subtitle: "I build software to help humans thrive."
    content: "I believe that software can be used to improve the state of the world despite it's challenges and potential dangers. I have a passion for developing applications that make the world a better place."
    image: /images/joe_pic.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "/images/resume.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/joedaws
        - icon: fab fa-twitter
          url: https://twitter.com/joedawsjr
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/joseph-daws-1a8b33183

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/joe_woods.jpg"
    content: |-
      I believe machine learning can be used to improve the state of the world despite its potential dangers. This belief guides my approach to building. Good software goes a step beyond solving a problem, it should enable humans to live a better life.

      I am currently a Senior Machine Learning Software Engineer at One Medical where I am working on automating labourous and monotonous tasks to give time back to health care providers so that they may better connect with their patients.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "AWS SageMaker"
        - "Docker"
        - "AWS Lambda"
        - "FastAPI"
        - "AWS ECS"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Senior Machine Learning Software Engineer"
        company: "One Medical"
        companyUrl: "https://onemedical.com"
        date: "October 2021 - present"
        info:
          enable: false
        featuredLink:
          enable: false
          name: "One Medical"
          url: "https://onemedical.com"
        content: "I am currently working as a software engineer at [One Medical](https://onemedical.com) where I am building machine learning powered applications to support an Electronic Health Record."

      - job: "Senior Machine Learning Engineer"
        company: "Lirio"
        companyUrl: "https://lirio.com"
        date: "April 2020 - October 2021"
        info:
          enable: false
        featuredLink:
          enable: true
          name: "ASGF Project"
          url: "https://github.com/joedaws/ASGF"
        content: |
          I researched and developed novel approaches to machine learning for behavioral change AI. I designed and developed an in-house experimenation platform as well as implemented core components of the training pipelines for a deep learning model.

          - [This repository](https://github.com/joedaws/ASGF) contains the source code reproducing the numerical examples presented in the paper An adaptive stochastic gradient-free approach for high-dimensional blackbox optimization.
          - [Here](https://github.com/joedaws/lde2021) is the official reopsitory for the paper ''Offline Policy Comparison under Limited Historical Agent-Environment Interactions'' that is available at https://arxiv.org/abs/2106.03934.

      - job: "Graduate Research Assistant"
        company: "University of Tennessee"
        companyUrl: "https://utk.edu"
        date: "Jan 2017 - April 2020"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          As a research assistant I designed, analyzed and implemented novel algorithms using
          approximation theory to solve a variety of problems in application domains including

          - image processing
          - signal denoising
          - classification

          More details can be found in my Ph.D. dissertation https://trace.tennessee.edu/utk_graddiss/5916/

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Ph.D. in Mathematics"
        school:
          name: "University of Tennessee, Knoxville"
          url: "https://utk.edu"
        date: "2016 - 2020"
        featuredLink:
          enable: true
          name: "Dissertation"
          url: "https://trace.tennessee.edu/utk_graddiss/5916/"

      - title: "M.S. Mathematics"
        school:
          name: "University of Tennessee, Knoxville"
          url: "https://utk.edu"
        date: "2013 - 2016"

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    title: "Recent Work"
    items:
      - title: Automated routing of faxed documents
        image: /images/fax_word.png
        content: Used Computer vision and deep learning to extract important information from incoming faxes. This service also automatically routes faxes to their correct final destination in an electronic health record (EHR) when the type is detected.
        featured:
          name: Tesseract
          link: https://github.com/tesseract-ocr/tesseract
        badges:
          - "Python"
          - "Tesseract"
          - "Terraform"
          - "AWS Lambda"
          - "AWS SNS/SQS"

      - title: Limited Data Estimator
        image: /images/lde.png
        content: Comparison of policies for contextual bandit problems using a set of limited historical interactions.
        badges:
          - "Python"
          - "Reinforcement Learning"
        links:
          - icon: fab fa-github
            url: https://github.com/joedaws/lde2021

      - title: Adaptive Stochastic gradient-free (ASGF) blackbox optimization
        image: /images/asgf.png
        content: A black-box optimization method for extremely high dimensional non-convex objective functions.
        badges:
          - "Python"
          - "Parallel processing (mpi4py)"
        links:
          - icon: fab fa-github
            url: https://github.com/joedaws/ASGF

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: "If you would like to contact me, feel free to email me. I can not guarentee an
    expedient response, but I'll do my best to reply."
    email: daws.joseph@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/joedaws
      linkedin: https://www.linkedin.com/in/joseph-daws-1a8b33183
      twitter: https://twitter.com/joedawsjr

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>

